/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdTicketsIndexImport } from './routes/projects/$projectId/tickets/index'
import { Route as ProjectsProjectIdTicketsCreateIndexImport } from './routes/projects/$projectId/tickets/create/index'
import { Route as ProjectsProjectIdTicketsTicketIdIndexImport } from './routes/projects/$projectId/tickets/$ticketId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdTicketsIndexRoute =
  ProjectsProjectIdTicketsIndexImport.update({
    id: '/projects/$projectId/tickets/',
    path: '/projects/$projectId/tickets/',
    getParentRoute: () => rootRoute,
  } as any)

const ProjectsProjectIdTicketsCreateIndexRoute =
  ProjectsProjectIdTicketsCreateIndexImport.update({
    id: '/projects/$projectId/tickets/create/',
    path: '/projects/$projectId/tickets/create/',
    getParentRoute: () => rootRoute,
  } as any)

const ProjectsProjectIdTicketsTicketIdIndexRoute =
  ProjectsProjectIdTicketsTicketIdIndexImport.update({
    id: '/projects/$projectId/tickets/$ticketId/',
    path: '/projects/$projectId/tickets/$ticketId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/tickets/': {
      id: '/projects/$projectId/tickets/'
      path: '/projects/$projectId/tickets'
      fullPath: '/projects/$projectId/tickets'
      preLoaderRoute: typeof ProjectsProjectIdTicketsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/tickets/$ticketId/': {
      id: '/projects/$projectId/tickets/$ticketId/'
      path: '/projects/$projectId/tickets/$ticketId'
      fullPath: '/projects/$projectId/tickets/$ticketId'
      preLoaderRoute: typeof ProjectsProjectIdTicketsTicketIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/tickets/create/': {
      id: '/projects/$projectId/tickets/create/'
      path: '/projects/$projectId/tickets/create'
      fullPath: '/projects/$projectId/tickets/create'
      preLoaderRoute: typeof ProjectsProjectIdTicketsCreateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/projects': typeof ProjectsIndexRoute
  '/users': typeof UsersIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tickets': typeof ProjectsProjectIdTicketsIndexRoute
  '/projects/$projectId/tickets/$ticketId': typeof ProjectsProjectIdTicketsTicketIdIndexRoute
  '/projects/$projectId/tickets/create': typeof ProjectsProjectIdTicketsCreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/projects': typeof ProjectsIndexRoute
  '/users': typeof UsersIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tickets': typeof ProjectsProjectIdTicketsIndexRoute
  '/projects/$projectId/tickets/$ticketId': typeof ProjectsProjectIdTicketsTicketIdIndexRoute
  '/projects/$projectId/tickets/create': typeof ProjectsProjectIdTicketsCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/projects/': typeof ProjectsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tickets/': typeof ProjectsProjectIdTicketsIndexRoute
  '/projects/$projectId/tickets/$ticketId/': typeof ProjectsProjectIdTicketsTicketIdIndexRoute
  '/projects/$projectId/tickets/create/': typeof ProjectsProjectIdTicketsCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/projects'
    | '/users'
    | '/projects/$projectId'
    | '/projects/$projectId/tickets'
    | '/projects/$projectId/tickets/$ticketId'
    | '/projects/$projectId/tickets/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/projects'
    | '/users'
    | '/projects/$projectId'
    | '/projects/$projectId/tickets'
    | '/projects/$projectId/tickets/$ticketId'
    | '/projects/$projectId/tickets/create'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/projects/'
    | '/users/'
    | '/projects/$projectId/'
    | '/projects/$projectId/tickets/'
    | '/projects/$projectId/tickets/$ticketId/'
    | '/projects/$projectId/tickets/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdTicketsIndexRoute: typeof ProjectsProjectIdTicketsIndexRoute
  ProjectsProjectIdTicketsTicketIdIndexRoute: typeof ProjectsProjectIdTicketsTicketIdIndexRoute
  ProjectsProjectIdTicketsCreateIndexRoute: typeof ProjectsProjectIdTicketsCreateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdTicketsIndexRoute: ProjectsProjectIdTicketsIndexRoute,
  ProjectsProjectIdTicketsTicketIdIndexRoute:
    ProjectsProjectIdTicketsTicketIdIndexRoute,
  ProjectsProjectIdTicketsCreateIndexRoute:
    ProjectsProjectIdTicketsCreateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/register",
        "/projects/",
        "/users/",
        "/projects/$projectId/",
        "/projects/$projectId/tickets/",
        "/projects/$projectId/tickets/$ticketId/",
        "/projects/$projectId/tickets/create/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/projects/$projectId/": {
      "filePath": "projects/$projectId/index.tsx"
    },
    "/projects/$projectId/tickets/": {
      "filePath": "projects/$projectId/tickets/index.tsx"
    },
    "/projects/$projectId/tickets/$ticketId/": {
      "filePath": "projects/$projectId/tickets/$ticketId/index.tsx"
    },
    "/projects/$projectId/tickets/create/": {
      "filePath": "projects/$projectId/tickets/create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
